car_models = [
    ("Camry", True),           # Japanese (Toyota)
    ("Mustang", False),        # American (Ford)
    ("Civic", True),           # Japanese (Honda)
    ("Corvette", False),       # American (Chevrolet)
    ("RX-7", True),            # Japanese (Mazda)
    ("Challenger", False),     # American (Dodge)
    ("Supra", True),           # Japanese (Toyota)
    ("Model S", False),        # American (Tesla)
    ("370Z", True),            # Japanese (Nissan)
    ("Escalade", False),       # American (Cadillac)
    ("Impreza", True),         # Japanese (Subaru)
    ("Charger", False),        # American (Dodge)
    ("Miata", True),           # Japanese (Mazda)
    ("Explorer", False),       # American (Ford)
    ("WRX", True),             # Japanese (Subaru)
    ("Camaro", False),         # American (Chevrolet)
    ("Skyline", True),         # Japanese (Nissan)
    ("Viper", False),          # American (Dodge)
    ("NSX", True),             # Japanese (Honda/Acura)
    ("Continental", False),     # American (Lincoln)
    ("Eclipse", True),         # Japanese (Mitsubishi)
    ("Silverado", False),      # American (Chevrolet)
    ("Lancer", True),          # Japanese (Mitsubishi)
    ("Model 3", False),        # American (Tesla)
    ("Celica", True),          # Japanese (Toyota)
    ("F-150", False),          # American (Ford)
    ("Integra", True),         # Japanese (Acura/Honda)
    ("Grand Cherokee", False),  # American (Jeep)
    ("RX-8", True),            # Japanese (Mazda)
    ("Model X", False),        # American (Tesla)
    ("BRZ", True),             # Japanese (Subaru)
    ("Ram 1500", False),       # American (Ram)
    ("GTR", True),             # Japanese (Nissan)
    ("Tahoe", False),          # American (Chevrolet)
    ("Prelude", True),         # Japanese (Honda)
    ("Wrangler", False),       # American (Jeep)
    ("EVO", True),             # Japanese (Mitsubishi)
    ("CT5", False),            # American (Cadillac)
    ("86", True),              # Japanese (Toyota)
    ("Model Y", False)         # American (Tesla)
]