# List of (city, is_east_meridian)
meridian_cities = [
    ("Greenwich", True),     # UK - Prime Meridian runs through Royal Observatory (0°)
    ("London", False),       # UK - City center just west of meridian (-0.1276°)
    ("Paris", True),        # France (2.3522° E)
    ("Le Havre", False),    # France (-0.1079° W)
    ("Dieppe", True),       # France (1.0794° E)
    ("Brighton", False),    # UK (-0.1372° W)
    ("Dunkirk", True),      # France (2.3770° E)
    ("Plymouth", False),    # UK (-4.1426° W)
    ("Lille", True),        # France (3.0573° E)
    ("Exeter", False),      # UK (-3.5339° W)
    ("Rouen", True),        # France (1.0993° E)
    ("Cambridge", True),    # UK (0.1313° E)
    ("Orleans", True),      # France (1.9093° E)
    ("Portsmouth", False),  # UK (-1.0872° W)
    ("Tours", False),       # France (-0.6848° W)
    ("Dover", True),        # UK (1.3134° E)
    ("Calais", True),       # France (1.8585° E)
    ("Southampton", False), # UK (-1.4043° W)
    ("Amiens", True),       # France (2.2967° E)
    ("Norwich", True),      # UK (1.2921° E)
    ("Valencia", False),    # Spain (-0.3763° W)
    ("Castellon", False),   # Spain (-0.0376° W)
    ("Algiers", True),      # Algeria (3.0588° E)
    ("Oran", False),        # Algeria (-0.6349° W)
    ("Grenada", False),     # Spain (-3.5986° W)
    ("Malaga", False),      # Spain (-4.4214° W)
    ("Almeria", False),     # Spain (-2.4684° W)
    ("Ghardaia", True),     # Algeria (3.6744° E)
    ("Tlemcen", False),     # Algeria (-1.3150° W)
    ("Colchester", True),   # UK (0.8990° E)
    ("Ipswich", True),      # UK (1.1550° E)
    ("Reading", False),     # UK (-0.9781° W)
    ("Oxford", False),      # UK (-1.2578° W)
    ("Leicester", False),   # UK (-1.1333° W)
    ("Nottingham", False),  # UK (-1.1581° W)
    ("Hull", False),        # UK (-0.3367° W)
    ("York", False),        # UK (-1.0872° W)
    ("Chelmsford", True),   # UK (0.4789° E)
    ("Eastbourne", True),   # UK (0.2902° E)
    ("Hastings", True)      # UK (0.5738° E)
]